require("plugins_config.lualine")
require("plugins_config.none-ls")
require("plugins_config.neo-tree")
require("plugins_config.telescope")
require("plugins_config.treesitter")
require("plugins_config.lsp")
require("plugins_config.hop")
require("plugins_config.tokyonight")
