-- require("plugins_config.lsp-config")
-- require("plugins_config.completions")
-- require("plugins_config.alpha")
require("plugins_config.lualine")
require("plugins_config.none-ls")
require("plugins_config.neo-tree")
require("plugins_config.telescope")
require("plugins_config.treesitter")
require("plugins_config.lsp")
require("plugins_config.toggle-term")
require("plugins_config.hop")
require("plugins_config.tokyonight")
-- require("plugins_config.neorg")
-- require("plugins_config.noice")
