local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
  s("homework", {
    t({
      "\\documentclass[11pt]{article}",
      "\\usepackage{hyperref}",
      "\\usepackage[utf8]{inputenc}",
      "\\usepackage{amsmath,amsthm,amsfonts,amssymb,amscd}",
      "\\usepackage{xeCJK}",
      "\\usepackage{physics}",
      "\\usepackage{multirow,booktabs}",
      "\\usepackage{fullpage}",
      "\\usepackage{lastpage}",
      "\\usepackage{unicode-math}",
      "\\usepackage{enumitem}",
      "\\usepackage{fancyhdr}",
      "\\usepackage{mathrsfs}",
      "\\usepackage{wrapfig}",
      "\\usepackage{setspace}",
      "\\usepackage{calc}",
      "\\usepackage{multicol}",
      "\\usepackage{cancel}",
      "\\usepackage[retainorgcmds]{IEEEtrantools}",
      "\\usepackage[margin=3cm]{geometry}",
      "\\DeclareMathAlphabet{\\mathcal}{OMS}{cmsy}{m}{n}",
      "\\let\\mathbb\\relax",
      "\\DeclareMathAlphabet{\\mathbb}{U}{msb}{m}{n}",
      "\\setlength{\\parindent}{0.0in}",
      "\\setlength{\\parskip}{0.05in}",
      "\\usepackage{empheq}",
      "\\usepackage{framed}",
      "\\usepackage[most]{tcolorbox}",
      "\\usepackage{xcolor}",
      "\\linespread{1.2}",
      "\\graphicspath{{./}}",
      "\\setCJKmainfont[AutoFakeBold=3, AutoFakeSlant=4]{BiauKaiTC}",
      "\\colorlet{shadecolor}{orange!15}",
      "\\geometry{margin=1in, headsep=0.25in}",
      "\\theoremstyle{definition}",
      "\\newtheorem{thr}{Theorem}",
      "\\newtheorem{lma}{Lemma}",
      "\\newtheorem{defn}{Definition}",
      "\\newtheorem{reg}{Rule}",
      "\\newtheorem{exer}{Exercise}",
      "\\newtheorem{note}{Note}",
      "\\newtheorem{asmp}{Assumption}",
      "",
      "\\begin{document}",
      "\\setcounter{section}{0}",
      "\\title{Your Title}",
      "\\author{Your Name}",
      "",
      "\\thispagestyle{empty}",
      "\\begin{center}",
      "  {\\large \\bf Document Title} \\\\",
      "  B12901022 廖冠豪",
      "\\end{center}",
      "",
      "\\end{document}",
    }),
  }),
}
